package com.example.prototype;

public enum TypeTravaux {
    TRAVAUXROUTIERS,
    TRAVAUXGAZELECTRICITE,
    CONSTRUCTIONRENOVATION,
    ENTRETIENPAYSAGER,
    TRAVAUXTRANSPORTPUBLIC,
    TRAVAUXSIGNALISATIONECLAIRAGE,
    TRAVAUXSOUTERRAINS,
    TRAVAUXRESIDENTIELS,
    ENTRETIENURBAIN,
    ENTRETIENRESEAUXTELECOMMUNICATION
}
